version: '2'

networks:
        ca:

services:
        tls-ca:
                image: hyperledger/fabric-ca:latest
                container_name: tls-ca
                environment:
                        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
                        - FABRIC_CA_SERVER_CA_NAME=tls-ca
                        - FABRIC_CA_SERVER_TLS_ENABLED=true
                        - FABRIC_CA_SERVER_PORT=7054
                        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
                ports:
                        - "7054:7054"
                command: sh -c 'fabric-ca-server start -d'
                volumes:
                        - ./ca/tls-ca:/etc/hyperledger/fabric-ca-server
                networks:
                        - ca

        org-ca:
                image: hyperledger/fabric-ca:latest
                container_name: org-ca
                environment:
                        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
                        - FABRIC_CA_SERVER_CA_NAME=org-ca
                        - FABRIC_CA_SERVER_TLS_ENABLED=true
                        - FABRIC_CA_SERVER_PORT=7054
                        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
                ports:
                        - "7055:7054"
                command: sh -c 'fabric-ca-server start -d'
                volumes:
                        - ./ca/org-ca:/etc/hyperledger/fabric-ca-server
                networks:
                        - ca

        ord-ca:
               image: hyperledger/fabric-ca:latest
               container_name: ord-ca
               environment:
                       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
                       - FABRIC_CA_SERVER_CA_NAME=ord-ca
                       - FABRIC_CA_SERVER_PORT=7054
                       - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
               ports:
                       - "7056:7054"
               command: sh -c 'fabric-ca-server start -d'
               volumes:
                       - ./ca/ord-ca:/etc/hyperledger/fabric-ca-server
               networks:
                       - ca
