---
Organizations:
    - &ORG
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ORG

        # ID to load the MSP definition as
        ID: ORGMSP

        MSPDir: PATH/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ORGMSP.admin', 'ORGMSP.peer', 'ORGMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ORGMSP.admin', 'ORGMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ORGMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ORGMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.ORG.example.com
              Port: 11051